name: Deploy React Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t wthug/interviewviz-react .

      - name: Publish Image to Docker hub
        run: docker push wthug/interviewviz-react:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: removing previous running container
        run: docker rm -f react-app-container

      - name: Pull image from docker hub
        run: docker pull wthug/interviewviz-react:latest

      - name: run docker container
        run: docker run -d -p 8080:80 --name react-app-container wthug/interviewviz-react
